import { Charity, CharityStatus, OrgType } from "@/types/charity";

export const mockCharities: Charity[] = [
  {
    id: "1",
    chainId: 1,
    ownerAddress: "0x4B2f...8C3d",
    name: "Kenya Education Trust",
    description: "Empowering communities through education in East Africa since 2018. Building schools, training teachers, and providing resources for underserved regions.",
    logoUrl: "https://ui-avatars.com/api/?name=Kenya+Education+Trust&background=0EA5E9&color=fff&size=120&bold=true",
    website: "https://kenyaeducationtrust.org",
    orgType: OrgType.Nonprofit,
    status: CharityStatus.Verified,
    kycVerified: true,
    campaignCount: 5,
    registeredAt: 1706140800,
  },
  {
    id: "2",
    chainId: 2,
    ownerAddress: "0x901c...4E7a",
    name: "Green Earth Foundation",
    description: "Environmental conservation and reforestation across South America and Southeast Asia.",
    logoUrl: "https://ui-avatars.com/api/?name=Green+Earth+Foundation&background=22C55E&color=fff&size=120&bold=true",
    website: "https://greenearthfoundation.org",
    orgType: OrgType.Nonprofit,
    status: CharityStatus.Verified,
    kycVerified: true,
    campaignCount: 3,
    registeredAt: 1709251200,
  },
  {
    id: "3",
    chainId: 3,
    ownerAddress: "0x2E8b...7F1c",
    name: "Global Health Initiative",
    description: "Delivering healthcare solutions to remote communities worldwide. Mobile clinics, medical supplies, and health education.",
    logoUrl: "https://ui-avatars.com/api/?name=Global+Health+Initiative&background=3B82F6&color=fff&size=120&bold=true",
    website: "https://globalhealthinitiative.org",
    orgType: OrgType.Church,
    status: CharityStatus.Verified,
    kycVerified: true,
    campaignCount: 4,
    registeredAt: 1704326400,
  },
  {
    id: "4",
    chainId: 4,
    ownerAddress: "0xC3d2...7eF9",
    name: "Code for Africa",
    description: "Technology education and digital literacy programs across Africa.",
    logoUrl: "https://ui-avatars.com/api/?name=Code+for+Africa&background=8B5CF6&color=fff&size=120&bold=true",
    website: "https://codeforafrica.org",
    orgType: OrgType.SocialEnterprise,
    status: CharityStatus.Verified,
    kycVerified: true,
    campaignCount: 2,
    registeredAt: 1711929600,
  },
  {
    id: "5",
    chainId: 5,
    ownerAddress: "0xA8b1...3cD4",
    name: "Global Aid Network",
    description: "Disaster relief and humanitarian aid for communities affected by natural disasters.",
    logoUrl: "https://ui-avatars.com/api/?name=Global+Aid+Network&background=D97706&color=fff&size=120&bold=true",
    website: "https://globalaidnetwork.org",
    orgType: OrgType.Church,
    status: CharityStatus.Verified,
    kycVerified: true,
    campaignCount: 3,
    registeredAt: 1707350400,
  },
];
