import { Charity, CharityStatus } from "@/types/charity";

export const mockCharities: Charity[] = [
  {
    id: "1",
    chainId: 1,
    ownerAddress: "0x4B2f...8C3d",
    name: "Kenya Education Trust",
    description: "Empowering communities through education in East Africa since 2018. Building schools, training teachers, and providing resources for underserved regions.",
    logoUrl: "/images/charities/kenya-edu.png",
    website: "https://kenyaeducationtrust.org",
    status: CharityStatus.Verified,
    kycVerified: true,
    campaignCount: 5,
    registeredAt: 1706140800,
  },
  {
    id: "2",
    chainId: 2,
    ownerAddress: "0x901c...4E7a",
    name: "Green Earth Foundation",
    description: "Environmental conservation and reforestation across South America and Southeast Asia.",
    logoUrl: "/images/charities/green-earth.png",
    website: "https://greenearthfoundation.org",
    status: CharityStatus.Verified,
    kycVerified: true,
    campaignCount: 3,
    registeredAt: 1709251200,
  },
  {
    id: "3",
    chainId: 3,
    ownerAddress: "0x2E8b...7F1c",
    name: "Global Health Initiative",
    description: "Delivering healthcare solutions to remote communities worldwide. Mobile clinics, medical supplies, and health education.",
    logoUrl: "/images/charities/global-health.png",
    website: "https://globalhealthinitiative.org",
    status: CharityStatus.Verified,
    kycVerified: true,
    campaignCount: 4,
    registeredAt: 1704326400,
  },
  {
    id: "4",
    chainId: 4,
    ownerAddress: "0xC3d2...7eF9",
    name: "Code for Africa",
    description: "Technology education and digital literacy programs across Africa.",
    logoUrl: "/images/charities/code-africa.png",
    website: "https://codeforafrica.org",
    status: CharityStatus.Verified,
    kycVerified: true,
    campaignCount: 2,
    registeredAt: 1711929600,
  },
  {
    id: "5",
    chainId: 5,
    ownerAddress: "0xA8b1...3cD4",
    name: "Global Aid Network",
    description: "Disaster relief and humanitarian aid for communities affected by natural disasters.",
    logoUrl: "/images/charities/global-aid.png",
    website: "https://globalaidnetwork.org",
    status: CharityStatus.Verified,
    kycVerified: true,
    campaignCount: 3,
    registeredAt: 1707350400,
  },
];
